create table if not exists public.programme_event_plans (
  id bigint generated by default as identity primary key,
  club_id text not null,
  week_start date not null,
  event_date date not null,
  event_id text not null,
  formation text not null default '3-1-4-2',
  availability jsonb not null default '{}'::jsonb,
  lineup jsonb not null default '[]'::jsonb,
  bench jsonb not null default '[]'::jsonb,
  notes text not null default '',
  updated_by uuid null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint programme_event_plans_club_event_unique unique (club_id, event_id)
);
create index if not exists programme_event_plans_week_idx on public.programme_event_plans (club_id, week_start);
create index if not exists programme_event_plans_date_idx on public.programme_event_plans (club_id, event_date);
